spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
